# Generated by Django 6.0.2 on 2026-04-12 16:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileImpression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('feed_position', models.PositiveSmallIntegerField()),
                ('ranking_score', models.FloatField()),
                ('session_id', models.CharField(db_index=True, max_length=64)),
                ('device_type', models.CharField(blank=True, max_length=20, null=True)),
                ('was_swiped', models.BooleanField(default=False)),
                ('swipe_action', models.CharField(choices=[('like', 'Like'), ('pass', 'Pass'), ('none', 'None')], default='none', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('viewed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impressions_received', to=settings.AUTH_USER_MODEL)),
                ('viewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impressions_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['viewer', 'timestamp'], name='admin_dashb_viewer__72795e_idx'), models.Index(fields=['viewed', 'timestamp'], name='admin_dashb_viewed__aef761_idx'), models.Index(fields=['session_id', 'timestamp'], name='admin_dashb_session_ef7e06_idx')],
            },
        ),
    ]
