# Generated by Django 6.0.2 on 2026-05-11 16:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0004_notificationemailtemplate_notificationemaillog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('case_opened', 'Case Opened'), ('owner_assigned', 'Owner Assigned'), ('owner_reassigned', 'Owner Reassigned'), ('owner_released', 'Owner Released'), ('status_changed', 'Status Changed'), ('notes_updated', 'Notes Updated'), ('action_recorded', 'Action Recorded'), ('closure_updated', 'Closure Updated'), ('case_closed', 'Case Closed'), ('case_reopened', 'Case Reopened')], max_length=40)),
                ('title', models.CharField(max_length=180)),
                ('detail', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_activity_logs', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='admin_dashboard.reportcase')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['case', '-created_at'], name='adm_case_act_idx'), models.Index(fields=['event_type', '-created_at'], name='adm_case_evt_idx')],
            },
        ),
    ]
