# Generated by Django 6.0.2 on 2026-03-14 19:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='notification',
            name='notificatio_recipie_a972ce_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='notificatio_recipie_684eac_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='notificatio_type_ea918f_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='notificatio_created_46ad24_idx',
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(fields=('recipient', 'type', 'object_id'), name='unique_notification_per_object'),
        ),
    ]
