# Generated by Django 6.0.2 on 2026-06-14 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notification_count_notification_metadata_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('welcome', 'Welcome to NouMatch'), ('new_like', 'New Like'), ('new_match', 'New Match'), ('new_message', 'New Message'), ('coup_de_coeur', 'Coup de Coeur'), ('report_received', 'Report Received'), ('report_reviewed', 'Report Reviewed'), ('report_action_taken', 'Action Taken on Report'), ('system', 'System Notification'), ('promotional', 'Promotional'), ('reminder', 'Reminder')], db_index=True, max_length=30),
        ),
    ]
