# Generated by Django 6.0.2 on 2026-03-03 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Match',
        ),
    ]
