# Generated by Django 6.0.2 on 2026-03-12 15:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matches', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('fake_profile', 'Fake Profile'), ('harassment', 'Harassment or Bullying'), ('inappropriate_content', 'Inappropriate Photos/Content'), ('scam', 'Scam or Fraud'), ('underage', 'User May Be Underage'), ('offensive_language', 'Offensive Language'), ('spam', 'Spam'), ('privacy_violation', 'Privacy Violation'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField(blank=True, help_text='Provide additional details about the issue')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('investigating', 'Under Investigation'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes for admin review')),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='reports/screenshots/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action_taken', models.TextField(blank=True, help_text='What action was taken (warning, ban, etc.)')),
                ('match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='matches.match')),
                ('reported_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_received', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_filed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='report_repo_status_844e8d_idx'), models.Index(fields=['reporter', 'reported_user'], name='report_repo_reporte_3c10db_idx')],
            },
        ),
    ]
