# Generated by Django 6.0.2 on 2026-03-11 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_is_online_user_last_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('free', 'Free Account'), ('premium', 'Premium Account'), ('god_mode', 'God Mode')], default='free', help_text='Account tier: Free, Premium, or God Mode', max_length=20),
        ),
    ]
