# Generated by Django 6.0.2 on 2026-03-20 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='interested_in',
        ),
    ]
