# Generated by Django 6.0.2 on 2026-04-04 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_otp_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='lock_until',
        ),
        migrations.AddField(
            model_name='user',
            name='profile_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('free', 'Free'), ('premium', 'Premium'), ('god_mode', 'God Mode')], default='free', max_length=20),
        ),
    ]
