# Generated by Django 6.0.2 on 2026-04-05 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_userstats'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
