# Generated by Django 6.0.2 on 2026-04-22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0016_user_score"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserEngagementScore",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("onboarding_points", models.IntegerField(default=0)),
                ("activity_points", models.IntegerField(default=0)),
                ("quality_points", models.IntegerField(default=0)),
                ("penalty_points", models.IntegerField(default=0)),
                ("total_points", models.IntegerField(default=0)),
                ("profile_completion_percent", models.PositiveSmallIntegerField(default=0)),
                ("engagement_score", models.PositiveSmallIntegerField(default=0)),
                ("quality_score", models.PositiveSmallIntegerField(default=0)),
                ("trust_score", models.PositiveSmallIntegerField(default=0)),
                ("overall_score", models.PositiveSmallIntegerField(default=0)),
                ("allow_perfect_score", models.BooleanField(default=False)),
                ("score_cap", models.PositiveSmallIntegerField(default=99)),
                ("breakdown", models.JSONField(blank=True, default=dict)),
                ("last_calculated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(on_delete=models.deletion.CASCADE, related_name="engagement_scorecard", to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={
                "verbose_name": "User Engagement Score",
                "verbose_name_plural": "User Engagement Scores",
            },
        ),
    ]
