# Generated by Django 6.0.2 on 2026-05-06 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_pendingregistration'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='feedvisibilityboost',
            new_name='users_feedv_viewer__bbf2e2_idx',
            old_name='users_feedvi_viewer__f4f6d2_idx',
        ),
        migrations.RenameIndex(
            model_name='feedvisibilityboost',
            new_name='users_feedv_target__336133_idx',
            old_name='users_feedvi_target__cd5378_idx',
        ),
    ]
