# Generated by Django 6.0.2 on 2026-03-29 15:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WaitlistStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_men_waiting', models.PositiveIntegerField(default=0)),
                ('total_women_waiting', models.PositiveIntegerField(default=0)),
                ('total_men_accepted', models.PositiveIntegerField(default=0)),
                ('total_women_accepted', models.PositiveIntegerField(default=0)),
                ('target_women_percentage', models.FloatField(default=55.0)),
                ('target_men_percentage', models.FloatField(default=45.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WaitlistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2)])),
                ('last_name', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2)])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Format de téléphone invalide', regex='^\\+?[0-9]{8,15}$')])),
                ('gender', models.CharField(choices=[('male', 'Homme'), ('female', 'Femme')], max_length=10)),
                ('how_did_you_hear', models.CharField(choices=[('social_media', 'Réseaux sociaux'), ('friend', "Recommandation d'un ami"), ('advertisement', 'Publicité'), ('search_engine', 'Moteur de recherche'), ('other', 'Autre')], max_length=20)),
                ('is_accepted', models.BooleanField(default=False)),
                ('position', models.PositiveIntegerField(blank=True, null=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['joined_at'],
                'indexes': [models.Index(fields=['gender', 'is_accepted'], name='waitlist_wa_gender_48b575_idx'), models.Index(fields=['joined_at'], name='waitlist_wa_joined__d0ced3_idx')],
            },
        ),
    ]
