# Generated by Django 6.0.2 on 2026-03-30 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waitlist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waitlistentry',
            name='how_did_you_hear',
        ),
        migrations.RemoveField(
            model_name='waitlistentry',
            name='phone_number',
        ),
    ]
