# Generated by Django 6.0.2 on 2026-04-16 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitlist', '0002_remove_waitlistentry_how_did_you_hear_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactedArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(choices=[('male', 'Homme'), ('female', 'Femme')], max_length=10)),
                ('removed_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(choices=[('accepted', 'Accepted'), ('refused', 'Refused'), ('contacted', 'Contacted & Removed'), ('other', 'Other')], max_length=50)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-removed_at'],
            },
        ),
        migrations.AddField(
            model_name='waitlistentry',
            name='contacted',
            field=models.BooleanField(default=False),
        ),
    ]
