# admin_dashboard/urls.py - CORRECTED (removed missing AdminDashboardMetricsView)

from django.urls import path
from .views import (
    AdminLoginView,
    AdminDashboardView,
    AdminUsersListView,
    AdminUserDetailView,
    AdminUserActionView,
    AdminBlockUserView,
    AdminBanUserView,
    AdminUnbanUserView,
    AdminDeactivateUserView,
    AdminReportResolveView,
    AdminReportsListView,
    AdminReportDetailView,
    AdminUpdateReportStatusView,
    AdminBanUserFromReportView,
    AdminSwipeStatsView,
    AdminSupportConversationListView,
    AdminSupportConversationDetailView,
    AdminReplyToSupportView,
    AdminFlaggedMessagesListView,
    AdminTakeActionOnFlaggedMessageView,
    AdminUserConversationsListView,
    AdminUserConversationDetailView,
    AdminUserConversationMessagesView,
    LogImpressionView,
    UpdateImpressionView,
    AdminAnalyticsImpressionsView,

)

urlpatterns = [
    path('admin_login/', AdminLoginView.as_view(), name='admin-login'),
    path('dashboard/', AdminDashboardView.as_view(), name='admin-dashboard'),
    path('users/list/', AdminUsersListView.as_view(), name='admin-users'),
    path('users/detail/<int:user_id>/', AdminUserDetailView.as_view(), name='admin-user-detail'),
    path('user_action/', AdminUserActionView.as_view(), name='admin-user-action'),
    path('resolve_report/', AdminReportResolveView.as_view(), name='admin-resolve-report'),
    path('user/block/', AdminBlockUserView.as_view(), name='admin-block-user'),
    path('user/ban/', AdminBanUserView.as_view(), name='admin-ban-user'),
    path('user/unban/', AdminUnbanUserView.as_view(), name='admin-unban-user'),
    path('user/deactivate/', AdminDeactivateUserView.as_view(), name='admin-deactivate-user'),
    path('reports/list/', AdminReportsListView.as_view(), name='admin-reports-list'),
    path('reports/detail/<int:pk>/', AdminReportDetailView.as_view(), name='admin-report-detail'),
    path('reports/update-status/<int:pk>/', AdminUpdateReportStatusView.as_view(), name='admin-report-update-status'),
    path('reports/ban-user/', AdminBanUserFromReportView.as_view(), name='admin-ban-from-report'),
    path('swipe-stats/', AdminSwipeStatsView.as_view(), name='admin-swipe-stats'),
    path('support-conversations/', AdminSupportConversationListView.as_view(), name='admin-support-conversations'),
    path('support-conversations/<int:pk>/', AdminSupportConversationDetailView.as_view(), name='admin-support-conversation-detail'),
    path('support-conversations/<int:pk>/reply/', AdminReplyToSupportView.as_view(), name='admin-support-reply'),
    path('flagged-messages/', AdminFlaggedMessagesListView.as_view(), name='admin-flagged-messages'),
    path('flagged-messages/<int:pk>/action/', AdminTakeActionOnFlaggedMessageView.as_view(), name='admin-flagged-action'),
    path('user-conversations/', AdminUserConversationsListView.as_view(), name='admin-user-conversations'),
    path('user-conversations/<int:pk>/', AdminUserConversationDetailView.as_view(), name='admin-user-conversation-detail'),
    path('user-conversations/<int:pk>/messages/', AdminUserConversationMessagesView.as_view(), name='admin-user-conversation-messages'),
    path('analytics/impression/', LogImpressionView.as_view(), name='log_impression'),
    path('analytics/impression/update/', UpdateImpressionView.as_view(), name='update_impression'),
    path('analytics/impressions/', AdminAnalyticsImpressionsView.as_view(), name='admin-analytics-impressions'),

]