# Generated by Django 6.0.2 on 2026-03-12 20:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0004_dailyswipe'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TodaySwipe',
            fields=[
            ],
            options={
                'verbose_name': "Today's Swipe",
                'verbose_name_plural': "Today's Swipes",
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('interactions.dailyswipe',),
        ),
        migrations.AddIndex(
            model_name='pass',
            index=models.Index(fields=['expires_at'], name='interaction_expires_83c3ed_idx'),
        ),
    ]
