# Generated by Django 6.0.2 on 2026-03-14 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0005_todayswipe_pass_interaction_expires_83c3ed_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='notification_sent',
            field=models.BooleanField(default=False),
        ),
    ]
